### ISSUE TITLE
flutter_map version 7 support ?

### ISSUE THREAD

**Issue by NicolasThaize** [tprebs/fluttermap_heatmap#22]
Actually the lib is not compatible with flutter-map in his 7th version. Is it something planned ?
thank you :)

**Comment by NicolasThaize** [comment]
#21 seem to make the job

**Comment by tprebs** [comment]
@NicolasThaize flutter-map v7 support has been added as part of release [0.0.8](https://pub.dev/packages/flutter_map_heatmap/versions/0.0.8)
