### ISSUE TITLE
[Web] Tiles without heatmap is grey.

### ISSUE THREAD

**Issue by sun-jiao** [tprebs/fluttermap_heatmap#6]
![image](https://github.com/tprebs/fluttermap_heatmap/assets/14086980/ef1ef913-0a85-45d3-ad9b-ca26cce98838)

**Comment by tprebs** [comment]
Thanks for the issue @sun-jiao. Interesting that this is only on web. I have a sneaking suspicion that this is an issue with TileLayer in flutter_map during web deployments but have not had a chance to look at it yet.

**Comment by RamyAssaf1** [comment]
Good day,
Facing the same issue on web, only when we add layers of heat map to flutter_heatmap. Anyone found a possible solution for this?

**Comment by tprebs** [comment]
@sun-jiao  @RamyAssaf1  This appears to be caused by flutters renderer for web behaving differently to that of android and ios when rendering rgba bitmaps. The fix for this is available in master
